const MS_SKILLS = [
  // === Core ===
  { id: 'cloud-solution-architect', name: 'Cloud Solution Architect', desc: 'Design well-architected Azure cloud systems', lang: 'core', category: 'patterns', source: 'microsoft-skills' },
  { id: 'copilot-sdk', name: 'Copilot SDK', desc: 'Build apps powered by GitHub Copilot', lang: 'core', category: 'ai', source: 'microsoft-skills' },
  { id: 'entra-agent-id', name: 'Entra Agent ID', desc: 'Create OAuth2-capable AI agent identities', lang: 'core', category: 'identity', source: 'microsoft-skills' },
  { id: 'frontend-design-review', name: 'Frontend Design Review', desc: 'Review and create distinctive frontend interfaces', lang: 'core', category: 'patterns', source: 'microsoft-skills' },
  { id: 'github-issue-creator', name: 'GitHub Issue Creator', desc: 'Convert notes/errors into structured GitHub issues', lang: 'core', category: 'patterns', source: 'microsoft-skills' },
  { id: 'mcp-builder', name: 'MCP Builder', desc: 'Build MCP servers for LLM tool integration', lang: 'core', category: 'ai', source: 'microsoft-skills' },
  { id: 'podcast-generation', name: 'Podcast Generation', desc: 'Generate podcast audio with Azure OpenAI Realtime API', lang: 'core', category: 'ai', source: 'microsoft-skills' },
  { id: 'skill-creator', name: 'Skill Creator', desc: 'Guide for creating effective skills for AI agents', lang: 'core', category: 'patterns', source: 'microsoft-skills' },
  { id: 'aspire-ts', name: 'Aspire TS', desc: '.NET Aspire orchestration for service discovery', lang: 'core', category: 'compute', source: 'microsoft-skills' },

  // === Python ===
  { id: 'agent-framework-azure-ai-py', name: 'Agent Framework Azure AI', desc: 'Persistent agents with hosted tools and MCP servers', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-contentsafety-py', name: 'Azure AI Content Safety', desc: 'Detect harmful content in text and images', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-contentunderstanding-py', name: 'Azure AI Content Understanding', desc: 'Multimodal extraction from documents/media', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'agents-v2-py', name: 'Agents v2', desc: 'Container agent patterns for Foundry Agents SDK', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-projects-py', name: 'Azure AI Projects', desc: 'High-level Foundry SDK with project client', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-search-documents-py', name: 'Azure Search Documents', desc: 'Vector, hybrid, and semantic search', lang: 'python', category: 'data', source: 'microsoft-skills' },
  { id: 'hosted-agents-v2-py', name: 'Hosted Agents v2', desc: 'Refreshed hosted agents with protocol libraries', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'm365-agents-py', name: 'M365 Agents', desc: 'Microsoft 365 Agents SDK with aiohttp hosting', lang: 'python', category: 'm365', source: 'microsoft-skills' },
  { id: 'azure-ai-ml-py', name: 'Azure AI ML', desc: 'ML SDK v2 for workspaces, jobs, models', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-textanalytics-py', name: 'Azure AI Text Analytics', desc: 'Sentiment, entities, PII, healthcare NLP', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-transcription-py', name: 'Azure AI Transcription', desc: 'Real-time and batch speech-to-text', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-translation-document-py', name: 'Azure AI Translation Document', desc: 'Batch document translation', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-translation-text-py', name: 'Azure AI Translation Text', desc: 'Real-time text translation', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-vision-imageanalysis-py', name: 'Azure AI Vision Image Analysis', desc: 'Captions, tags, OCR, object detection', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-voicelive-py', name: 'Azure AI VoiceLive', desc: 'Real-time bidirectional voice AI', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-speech-to-text-rest-py', name: 'Azure Speech to Text REST', desc: 'Speech-to-text REST API', lang: 'python', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-cosmos-db-py', name: 'Azure Cosmos DB', desc: 'FastAPI service layer with partition strategies', lang: 'python', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-cosmos-py', name: 'Azure Cosmos', desc: 'Document CRUD, queries, containers', lang: 'python', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-data-tables-py', name: 'Azure Data Tables', desc: 'NoSQL key-value storage', lang: 'python', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-blob-py', name: 'Azure Storage Blob', desc: 'Upload, download, container management', lang: 'python', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-file-datalake-py', name: 'Azure Storage File Data Lake', desc: 'Hierarchical file systems for big data', lang: 'python', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-file-share-py', name: 'Azure Storage File Share', desc: 'SMB file shares and cloud operations', lang: 'python', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-queue-py', name: 'Azure Storage Queue', desc: 'Message queuing and task distribution', lang: 'python', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-eventgrid-py', name: 'Azure Event Grid', desc: 'Event publishing, event-driven architectures', lang: 'python', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-eventhub-py', name: 'Azure Event Hub', desc: 'High-throughput streaming', lang: 'python', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-messaging-webpubsubservice-py', name: 'Azure Web PubSub Service', desc: 'Real-time messaging, WebSocket', lang: 'python', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-servicebus-py', name: 'Azure Service Bus', desc: 'Queues, topics, enterprise messaging', lang: 'python', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-identity-py', name: 'Azure Identity', desc: 'DefaultAzureCredential and managed identity', lang: 'python', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-keyvault-py', name: 'Azure Key Vault', desc: 'Secrets, keys, certificates management', lang: 'python', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-monitor-ingestion-py', name: 'Azure Monitor Ingestion', desc: 'Custom logs via Logs Ingestion API', lang: 'python', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'azure-monitor-opentelemetry-exporter-py', name: 'Azure Monitor OpenTelemetry Exporter', desc: 'Export to Application Insights', lang: 'python', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'azure-monitor-opentelemetry-py', name: 'Azure Monitor OpenTelemetry', desc: 'One-line App Insights setup', lang: 'python', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'azure-monitor-query-py', name: 'Azure Monitor Query', desc: 'Query Log Analytics and metrics', lang: 'python', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'azure-appconfiguration-py', name: 'Azure App Configuration', desc: 'Centralized config, feature flags', lang: 'python', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-containerregistry-py', name: 'Azure Container Registry', desc: 'Manage container images', lang: 'python', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-mgmt-apicenter-py', name: 'Azure Mgmt API Center', desc: 'API inventory and metadata governance', lang: 'python', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-mgmt-apimanagement-py', name: 'Azure Mgmt API Management', desc: 'APIM services, APIs, policies', lang: 'python', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-mgmt-botservice-py', name: 'Azure Mgmt Bot Service', desc: 'Create and manage Azure Bot resources', lang: 'python', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-mgmt-fabric-py', name: 'Azure Mgmt Fabric', desc: 'Microsoft Fabric capacities', lang: 'python', category: 'data', source: 'microsoft-skills' },
  { id: 'fastapi-router-py', name: 'FastAPI Router', desc: 'CRUD operations with auth dependencies', lang: 'python', category: 'patterns', source: 'microsoft-skills' },
  { id: 'pydantic-models-py', name: 'Pydantic Models', desc: 'Base, Create, Update, Response model variants', lang: 'python', category: 'patterns', source: 'microsoft-skills' },

  // === TypeScript ===
  { id: 'azure-ai-contentsafety-ts', name: 'Azure AI Content Safety', desc: 'Moderate text and images', lang: 'typescript', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-document-intelligence-ts', name: 'Azure AI Document Intelligence', desc: 'Extract from invoices/receipts/forms', lang: 'typescript', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-projects-ts', name: 'Azure AI Projects', desc: 'Foundry client with agents', lang: 'typescript', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-translation-ts', name: 'Azure AI Translation', desc: 'Text translation and document batch', lang: 'typescript', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-voicelive-ts', name: 'Azure AI VoiceLive', desc: 'Real-time voice AI with WebSocket', lang: 'typescript', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-search-documents-ts', name: 'Azure Search Documents', desc: 'Vector, hybrid, semantic search', lang: 'typescript', category: 'data', source: 'microsoft-skills' },
  { id: 'm365-agents-ts', name: 'M365 Agents', desc: 'AgentApplication routing with Express', lang: 'typescript', category: 'm365', source: 'microsoft-skills' },
  { id: 'azure-cosmos-ts', name: 'Azure Cosmos', desc: 'Document CRUD and bulk operations', lang: 'typescript', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-postgres-ts', name: 'Azure PostgreSQL', desc: 'PostgreSQL connections with pooling', lang: 'typescript', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-blob-ts', name: 'Azure Storage Blob', desc: 'Upload, download, SAS tokens', lang: 'typescript', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-file-share-ts', name: 'Azure Storage File Share', desc: 'SMB shares and file operations', lang: 'typescript', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-queue-ts', name: 'Azure Storage Queue', desc: 'Send, receive, visibility timeout', lang: 'typescript', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-eventhub-ts', name: 'Azure Event Hub', desc: 'High-throughput streaming', lang: 'typescript', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-servicebus-ts', name: 'Azure Service Bus', desc: 'Queues, topics, dead-letter handling', lang: 'typescript', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-web-pubsub-ts', name: 'Azure Web PubSub', desc: 'WebSocket real-time features', lang: 'typescript', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-appconfiguration-ts', name: 'Azure App Configuration', desc: 'Settings and feature flags', lang: 'typescript', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-identity-ts', name: 'Azure Identity', desc: 'DefaultAzureCredential and browser login', lang: 'typescript', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-keyvault-keys-ts', name: 'Azure Key Vault Keys', desc: 'Key operations and rotation', lang: 'typescript', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-keyvault-secrets-ts', name: 'Azure Key Vault Secrets', desc: 'Store and retrieve secrets', lang: 'typescript', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-microsoft-playwright-testing-ts', name: 'Azure Playwright Testing', desc: 'Scale browser tests', lang: 'typescript', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-monitor-opentelemetry-ts', name: 'Azure Monitor OpenTelemetry', desc: 'Tracing, metrics, logs', lang: 'typescript', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'frontend-ui-dark-ts', name: 'Frontend UI Dark', desc: 'Vite + React + Tailwind dark design system', lang: 'typescript', category: 'patterns', source: 'microsoft-skills' },
  { id: 'react-flow-node-ts', name: 'React Flow Node', desc: 'Custom nodes with TypeScript/Zustand', lang: 'typescript', category: 'patterns', source: 'microsoft-skills' },
  { id: 'zustand-store-ts', name: 'Zustand Store', desc: 'TypeScript state management patterns', lang: 'typescript', category: 'patterns', source: 'microsoft-skills' },

  // === Java ===
  { id: 'azure-ai-anomalydetector-java', name: 'Azure AI Anomaly Detector', desc: 'Time-series anomaly detection', lang: 'java', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-contentsafety-java', name: 'Azure AI Content Safety', desc: 'Text/image analysis with blocklists', lang: 'java', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-formrecognizer-java', name: 'Azure AI Form Recognizer', desc: 'Extract text, tables, key-values', lang: 'java', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-projects-java', name: 'Azure AI Projects', desc: 'Foundry project management', lang: 'java', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-vision-imageanalysis-java', name: 'Azure AI Vision Image Analysis', desc: 'Captions, OCR, object detection', lang: 'java', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-voicelive-java', name: 'Azure AI VoiceLive', desc: 'Real-time voice conversations', lang: 'java', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-communication-callautomation-java', name: 'Azure Communication Call Automation', desc: 'IVR, call routing, recording', lang: 'java', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-communication-callingserver-java', name: 'Azure Communication Calling Server', desc: 'Legacy calling server', lang: 'java', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-communication-chat-java', name: 'Azure Communication Chat', desc: 'Threading, messaging, read receipts', lang: 'java', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-communication-common-java', name: 'Azure Communication Common', desc: 'Token credentials, user identifiers', lang: 'java', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-communication-sms-java', name: 'Azure Communication SMS', desc: 'SMS notifications and OTP', lang: 'java', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-cosmos-java', name: 'Azure Cosmos', desc: 'NoSQL operations, global distribution', lang: 'java', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-data-tables-java', name: 'Azure Data Tables', desc: 'Table Storage and Cosmos DB Table API', lang: 'java', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-blob-java', name: 'Azure Storage Blob', desc: 'Upload, download, streaming', lang: 'java', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-eventgrid-java', name: 'Azure Event Grid', desc: 'Event publishing, pub/sub patterns', lang: 'java', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-eventhub-java', name: 'Azure Event Hub', desc: 'High-throughput streaming', lang: 'java', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-messaging-webpubsub-java', name: 'Azure Web PubSub', desc: 'WebSocket messaging', lang: 'java', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-identity-java', name: 'Azure Identity', desc: 'DefaultAzureCredential, managed identity', lang: 'java', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-security-keyvault-keys-java', name: 'Azure Key Vault Keys', desc: 'RSA/EC keys, HSM operations', lang: 'java', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-security-keyvault-secrets-java', name: 'Azure Key Vault Secrets', desc: 'Password and API key storage', lang: 'java', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-appconfiguration-java', name: 'Azure App Configuration', desc: 'Settings, feature flag management', lang: 'java', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-compute-batch-java', name: 'Azure Compute Batch', desc: 'Large-scale parallel and HPC jobs', lang: 'java', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-monitor-ingestion-java', name: 'Azure Monitor Ingestion', desc: 'Custom logs via Data Collection Rules', lang: 'java', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'azure-monitor-opentelemetry-exporter-java', name: 'Azure Monitor OpenTelemetry Exporter', desc: 'Traces, metrics, logs export', lang: 'java', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'azure-monitor-query-java', name: 'Azure Monitor Query', desc: 'Kusto queries, Log Analytics', lang: 'java', category: 'monitoring', source: 'microsoft-skills' },

  // === Rust ===
  { id: 'azure-identity-rust', name: 'Azure Identity', desc: 'DeveloperToolsCredential, managed identity', lang: 'rust', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-keyvault-certificates-rust', name: 'Azure Key Vault Certificates', desc: 'Create and manage certificates', lang: 'rust', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-keyvault-keys-rust', name: 'Azure Key Vault Keys', desc: 'RSA/EC keys, sign/verify', lang: 'rust', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-keyvault-secrets-rust', name: 'Azure Key Vault Secrets', desc: 'Password and API key management', lang: 'rust', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-cosmos-rust', name: 'Azure Cosmos', desc: 'Document CRUD and partitioning', lang: 'rust', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-storage-blob-rust', name: 'Azure Storage Blob', desc: 'Upload, download, streaming', lang: 'rust', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-eventhub-rust', name: 'Azure Event Hub', desc: 'High-throughput streaming, batching', lang: 'rust', category: 'messaging', source: 'microsoft-skills' },

  // === .NET ===
  { id: 'azure-ai-document-intelligence-dotnet', name: 'Azure AI Document Intelligence', desc: 'Extract text/tables from documents', lang: 'dotnet', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-openai-dotnet', name: 'Azure AI OpenAI', desc: 'Chat, embeddings, image generation', lang: 'dotnet', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-projects-dotnet', name: 'Azure AI Projects', desc: 'Foundry project client with agents', lang: 'dotnet', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-ai-voicelive-dotnet', name: 'Azure AI VoiceLive', desc: 'Real-time voice AI with WebSocket', lang: 'dotnet', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-mgmt-weightsandbiases-dotnet', name: 'Azure Mgmt Weights and Biases', desc: 'ML experiment tracking', lang: 'dotnet', category: 'ai', source: 'microsoft-skills' },
  { id: 'azure-search-documents-dotnet', name: 'Azure Search Documents', desc: 'Full-text, vector, semantic search', lang: 'dotnet', category: 'data', source: 'microsoft-skills' },
  { id: 'm365-agents-dotnet', name: 'M365 Agents', desc: 'ASP.NET Core hosting with Copilot Studio', lang: 'dotnet', category: 'm365', source: 'microsoft-skills' },
  { id: 'azure-mgmt-fabric-dotnet', name: 'Azure Mgmt Fabric', desc: 'Provision and scale Fabric capacities', lang: 'dotnet', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-resource-manager-cosmosdb-dotnet', name: 'Azure Resource Manager Cosmos DB', desc: 'Cosmos DB ARM with RBAC', lang: 'dotnet', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-resource-manager-mysql-dotnet', name: 'Azure Resource Manager MySQL', desc: 'MySQL Flexible Server', lang: 'dotnet', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-resource-manager-postgresql-dotnet', name: 'Azure Resource Manager PostgreSQL', desc: 'PostgreSQL Flexible Server', lang: 'dotnet', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-resource-manager-redis-dotnet', name: 'Azure Resource Manager Redis', desc: 'Redis cache and geo-replication', lang: 'dotnet', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-resource-manager-sql-dotnet', name: 'Azure Resource Manager SQL', desc: 'SQL servers, elastic pools', lang: 'dotnet', category: 'data', source: 'microsoft-skills' },
  { id: 'azure-eventgrid-dotnet', name: 'Azure Event Grid', desc: 'Event publishing and CloudEvents', lang: 'dotnet', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-eventhub-dotnet', name: 'Azure Event Hub', desc: 'High-throughput streaming', lang: 'dotnet', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-servicebus-dotnet', name: 'Azure Service Bus', desc: 'Queues, topics, dead-letter handling', lang: 'dotnet', category: 'messaging', source: 'microsoft-skills' },
  { id: 'azure-identity-dotnet', name: 'Azure Identity', desc: 'DefaultAzureCredential, managed identity', lang: 'dotnet', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-security-keyvault-keys-dotnet', name: 'Azure Key Vault Keys', desc: 'Key creation, encryption', lang: 'dotnet', category: 'identity', source: 'microsoft-skills' },
  { id: 'microsoft-azure-webjobs-extensions-authentication-events-dotnet', name: 'Azure WebJobs Auth Events', desc: 'Custom claims, token enrichment', lang: 'dotnet', category: 'identity', source: 'microsoft-skills' },
  { id: 'azure-maps-search-dotnet', name: 'Azure Maps Search', desc: 'Geocoding, routing, map tiles', lang: 'dotnet', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-mgmt-apicenter-dotnet', name: 'Azure Mgmt API Center', desc: 'API inventory, governance', lang: 'dotnet', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-mgmt-apimanagement-dotnet', name: 'Azure Mgmt API Management', desc: 'APIM services, policies', lang: 'dotnet', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-mgmt-botservice-dotnet', name: 'Azure Mgmt Bot Service', desc: 'Bot resources, channel management', lang: 'dotnet', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-resource-manager-durabletask-dotnet', name: 'Azure Resource Manager Durable Task', desc: 'Schedulers, task hubs', lang: 'dotnet', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-resource-manager-playwright-dotnet', name: 'Azure Resource Manager Playwright', desc: 'Testing workspaces, quotas', lang: 'dotnet', category: 'compute', source: 'microsoft-skills' },
  { id: 'azure-mgmt-applicationinsights-dotnet', name: 'Azure Mgmt Application Insights', desc: 'Application Insights components', lang: 'dotnet', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'azure-mgmt-arizeaiobservabilityeval-dotnet', name: 'Azure Mgmt Arize AI Observability Eval', desc: 'ML observability', lang: 'dotnet', category: 'monitoring', source: 'microsoft-skills' },
  { id: 'azure-mgmt-mongodbatlas-dotnet', name: 'Azure Mgmt MongoDB Atlas', desc: 'MongoDB Atlas management', lang: 'dotnet', category: 'data', source: 'microsoft-skills' },
]

export function getMsSkills() {
  return MS_SKILLS
}

export function getMsSkillCategories() {
  return {
    ai: 'AI & ML',
    data: 'Data & Storage',
    messaging: 'Messaging & Events',
    identity: 'Identity & Security',
    monitoring: 'Monitoring',
    compute: 'Compute & Infra',
    m365: 'Microsoft 365',
    patterns: 'Patterns & Frameworks',
  }
}

export function getMsSkillLangs() {
  return {
    python: 'Python',
    dotnet: '.NET',
    typescript: 'TypeScript',
    java: 'Java',
    rust: 'Rust',
    core: 'Core',
  }
}
